### ISSUE TITLE
API  updates by 2020

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/fmi2#11]
The use of FMI's open data no longer requires registration.

Registered users should switch over to the new addresses by the end of 2019 in order to use the service. Addresses that include the API key of the Finnish Meteorological Institute will no longer be operational after 2019.

The new addresses are: 

https://opendata.fmi.fi/wfs (Download service - WFS) 
https://openwms.fmi.fi/geoserver/wms (View service - WMS)

**Comment by jlehtoma** [comment]
Thanks! `fmi2` already uses the WFS address above (should use https though) and does not require API keys. Or am I missing something here?

**Comment by antagomir** [comment]
Ah right. I just received email from FMI today with that message and missed that this was the same issue that was already solved earlier.
