### ISSUE TITLE
Fix fmi_stations()

### ISSUE THREAD

**Issue by jlehtoma** [rOpenGov/fmi2#12]
FMI has updated their webpages and currently `fmi_stations()` is unable to scrape the stations list. Fix scraping or find another way of getting the stations list.

**Comment by jlehtoma** [comment]
Stored query `fmi::ef::stations` just might do the trick so there would be no need for scraping.

**Comment by pitkant** [comment]
I noticed the same thing while doing the PR for Github Actions. The main issue that failed was vignette rebuilding and `fmi_stations()` function in specific, would replacing it with `fyi::ef::stations` do the trick?

**Comment by jlehtoma** [comment]
I took a quick look at `fmi::ef::stations` and I think it can be made to work, but this takes a little more effort than I was expecting. The observation station type (group / network) gets lost in the standard WFS -> GML -> sf-object translation pipeline. More specifically, the group identity is stored in `<ef:belongsTo>` element's attribute values which are not read in by `sf::st_read()`. So this information would have to be parsed from the WFS response object before it saved as a GML file an read back in.

**Comment by jlehtoma** [comment]
FIxed in 357ab194edcc4f44a3c50d391f1f0f459743d6f5
