### ISSUE TITLE
Interactive function + wrapper functions

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/fmi2#18]
Similar to sotkanet package's interactive function (rOpenGov/sotkanet#20), that drew inspiration from eurostat package's simple implementation and pxweb package's more complex implementation, vipunen could have an interactive function that would list available resources and datasets. This would provide ease-of-use to the end user and maybe crystallize the data-flows (input and output) in the package

If the need arises, write new wrapper functions for existing functions. Use snake_case for new functions, with format action_qualifier (e.g. get_data). See rOpenGov/sotkanet#18 for background

**Comment by Allaht2** [comment]
Addressed in PR #23 and in commits  9c54959, b266e20, 83b2b42 and ec7b57e.
