### ISSUE TITLE
Data citation

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/fmi2#19]
We should strive to implement [FORCE11 Joint Declaration of Data Citation Principles](https://force11.org/info/joint-declaration-of-data-citation-principles-final/) in our packages that retrieve data from APIs. See [rOpenGov/sotkanet#16](https://github.com/rOpenGov/sotkanet/issues/16) and similar issue and PR in eurostat: [rOpenGov/eurostat#268](https://github.com/rOpenGov/eurostat/issues/268) and [rOpenGov/eurostat#270](https://github.com/rOpenGov/eurostat/pull/270)

See FMI website for information on how they would want the data to be cited, or if there is no explicit instructions ask for one via email.

**Comment by Allaht2** [comment]
Addressed in PR #23 and in commit aa548aa.
