### ISSUE TITLE
Software citation

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/fmi2#20]
We should strive to implement [FORCE11 Software citation principles](https://force11.org/info/software-citation-principles-published-2016/) in our work, making it as simple as possible for users to cite our software package if they use it to retrieve data for their publications. See [rOpenGov/eurostat#275](https://github.com/rOpenGov/eurostat/issues/275) for some background info.

* [x]  Use cffr package to create a cff file for the repository: https://docs.ropensci.org/cffr/articles/cffr.html#creating-a-citation-cff-file-for-my-r-package
* [x]  Make sure that the output of `citation("fmi2")` is up to date and follows similar format as other packages, such as sotkanet or eurostat
* [x]  Make sure that package citation info is included in all vignettes and README

**Comment by pitkant** [comment]
Bibtex reference types: https://bibtex.eu/types/misc/

Bibtex supported fields: https://bibtex.eu/fields/

**Comment by Allaht2** [comment]
Addressed in PR #23 and in commits e4f8899, c0405ef and 6c1db42.
