### ISSUE TITLE
Data caching + reading local files

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/fmi2#22]
It might be a good idea to implement data caching in fmi2, similar to rOpenGov/sotkanet#14. Additionally, implementing this might make it easier to implement functionality related to reading files locally, i.e. if you have a downloaded .csv file that contains the same data as the API does.

**Comment by Allaht2** [comment]
Addressed in PR #23. Support for caching added in commits 4fa8bfd and 0d75e1a.
