### ISSUE TITLE
Documentation issue - bad URL

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/fmi2#9]
CRAN checks give:

Found the following (possibly) invalid URLs:
  URL: http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0
    From: man/fmi_api.Rd
    Status: 400
    Message: Bad Request

**Comment by jlehtoma** [comment]
This is a partial URL from the function docs and thus doesn't work. I guess it's not really needed, so I can just remove it from the docs.

**Comment by antagomir** [comment]
Would help since currently the automated CRAN checks fail at this point.

**Comment by jlehtoma** [comment]
Fixed in 8abc0d3a20b906369ae19f1905e447937b1adc8e
